### ISSUE TITLE
Building WinCairo following readme fails due to path issues

### ISSUE THREAD

**Issue by iangrunert** [WebKitForWindows/docker-webkit-dev#311]
Following the README to build failed, it wasn't able to find MSVC. Instead of creating the devenv.com file, I ran:

```
C:\MSVS\VC\Auxiliary\Build\vcvars64.bat
```

to set the appropriate environment variables to use MSVC on the command line which unblocked the build. Should I submit a PR to update the README?

**Comment by Makeshift** [comment]
Mine failed even earlier, because `svn` isn't included in the image.

Sadly, even after installing svn and getting checked out, I wasn't able to compile due to a missing `WebKitSupportLibrary.zip`. Every link on the internet (including Webkit's own guide) points you at: https://developer.apple.com/opensource/internet/webkit_sptlib_agree.html

which no longer exists. Having had a trawl through internet archive, I was able to find that submitting the form that was there would result in a POST:

```
curl 'https://developer.apple.com/file/' -X POST \
 -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0' \
 -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' \
 -H 'Accept-Language: en-GB,en;q=0.5' \
 -H 'Accept-Encoding: gzip, deflate, br' \
 -H 'Referer: https://developer.apple.com/opensource/internet/webkit_sptlib_agree.html' \
 -H 'Content-Type: application/x-www-form-urlencoded' \
 -H 'Origin: https://developer.apple.com' \
 -H 'DNT: 1' \
 -H 'Connection: keep-alive' \
 -H 'Upgrade-Insecure-Requests: 1' \
 -H 'Sec-Fetch-Dest: document' \
 -H 'Sec-Fetch-Mode: navigate' \
 -H 'Sec-Fetch-Site: same-origin' \
 -H 'Sec-Fetch-User: ?1' \
 -H 'Pragma: no-cache' \
 -H 'Cache-Control: no-cache' \
 -H 'TE: trailers' --data-raw 'file=webkitsupportlibrary&agree=Yes'
```

which also no longer works. So I gave up trying to build webkit at that point.

Good luck, future travellers.

**Comment by fujii** [comment]
WebKitSupportLibrary.zip was only for the deprecated Apple Windows port.
https://docs.webkit.org/Ports/WindowsPort.html is the current document.

**Comment by Makeshift** [comment]
> WebKitSupportLibrary.zip was only for the deprecated Apple Windows port. [docs.webkit.org/Ports/WindowsPort.html](https://docs.webkit.org/Ports/WindowsPort.html) is the current document.

Thanks! Googling 'compile webkit on Windows' brings me to [this doc](https://webkit.org/webkit-on-windows/) and [this doc](https://webkit.org/building-webkit-on-windows/), which definitely causes some confusion.

**Comment by donny-dont** [comment]
Updated README at #367 which would hopefully resolve this @iangrunert
